filebeat.inputs:
  - type: log
    paths:
      - /var/log/*.log
    fields:
      log_type: application
    json.keys_under_root: false

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  pipeline: "pipeline_logs"

setup.kibana:
  host: "http://kibana:5601"

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
